import {defineField, defineType} from 'sanity'

export default defineType({
  name: 'team',
  title: 'Team',
  type: 'document',
  fields: [
    defineField({
      name: 'name',
      title: 'Name',
      type: 'string',
      validation: Rule => Rule.required(),
    }),
    defineField({
      name: 'profileSummary',
      title: 'Profile Summary',
      type: 'text',
      rows: 4,
    }),
    defineField({
      name: 'trainingAndCertifications',
      title: 'Training and Certifications',
      type: 'array',
      of: [{ type: 'string' }],
      hidden: ({document}) => document?.type !== 'civilian',
    }),
    defineField({
      name: 'instructorCertifications',
      title: 'Instructor/Trainer Certifications',
      type: 'array',
      of: [{ type: 'string' }],
      hidden: ({document}) => document?.type !== 'civilian',
    }),
    defineField({
      name: 'shortCourses',
      title: 'Short Courses',
      type: 'array',
      of: [{ type: 'string' }],
      hidden: ({document}) => document?.type !== 'civilian',
    }),
    defineField({
      name: 'professionalMemberships',
      title: 'Professional Memberships',
      type: 'array',
      of: [{ type: 'string' }],
      hidden: ({document}) => document?.type !== 'civilian',
    }),
    defineField({
      name: 'careerMilestones',
      title: 'Career Milestones',
      type: 'array',
      of: [{ type: 'blockContent' }],
      hidden: ({document}) => document?.type !== 'civilian',
    }),
    defineField({
      name: 'hseLeadership',
      title: 'HSE Leadership',
      type: 'array',
      of: [{ type: 'blockContent' }],
      hidden: ({document}) => document?.type !== 'civilian',
    }),
    defineField({
      name: 'educationalBackground',
      title: 'Educational Background',
      type: 'array',
      of: [{ type: 'string' }],
      hidden: ({document}) => document?.type !== 'civilian',
    }),
    defineField({
      name: 'currentRole',
      title: 'Current Role',
      type: 'string',
      hidden: ({document}) => document?.type !== 'civilian',
    }),
    defineField({
      name: 'keyAchievements',
      title: 'Key Achievements',
      type: 'array',
      of: [{ type: 'blockContent' }],
      hidden: ({document}) => document?.type !== 'civilian',
    }),
    defineField({
      name: 'scopeOfServices',
      title: 'Scope of Services',
      type: 'array',
      of: [{ type: 'blockContent' }],
      hidden: ({document}) => document?.type !== 'civilian',
    }),
    defineField({
      name: 'professionalMaritimeCourses',
      title: 'Professional Maritime Courses',
      type: 'array',
      of: [{ type: 'string' }],
      hidden: ({document}) => document?.type !== 'military',
    }),
    defineField({
      name: 'militaryTraining',
      title: 'Military Training',
      type: 'array',
      of: [{ type: 'string' }],
      hidden: ({document}) => document?.type !== 'military',
    }),
    defineField({
      name: 'militaryUnitsServed',
      title: 'Military Units Served',
      type: 'array',
      of: [{ type: 'string' }],
      hidden: ({document}) => document?.type !== 'military',
    }),
    defineField({
      name: 'weaponsAndExplosives',
      title: 'Weapons and Explosives',
      type: 'array',
      of: [{ type: 'string' }],
      hidden: ({document}) => document?.type !== 'military',
    }),
    defineField({
      name: 'militaryOperations',
      title: 'Military Operations',
      type: 'array',
      of: [{ type: 'string' }],
      hidden: ({document}) => document?.type !== 'military',
    }),
    defineField({
      name: 'postMilitaryServiceExperience',
      title: 'Post-Military Service Experience',
      type: 'array',
      of: [{ type: 'blockContent' }],
      hidden: ({document}) => document?.type !== 'military',
    }),
    defineField({
      name: 'hobbies',
      title: 'Hobbies',
      type: 'array',
      of: [{ type: 'string' }],
      hidden: ({document}) => document?.type !== 'military',
    }),
  ],
})
